services:
  django_drf:
    image: memphistools/public_repo:dummy_django_restframework
    container_name: django_drf
    command:
      sh -c "gunicorn dummy_django_restframework.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/media
    expose:
      - 8000
    environment:
      - DEBUG
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - CORS_ALLOWED_ORIGINS
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_ENGINE
      - POSTGRES_PORT

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/media
      - ./certs:/etc/nginx/certs
    ports:
      - 443:443
    depends_on:
      - django_drf

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  media_volume:
  static_volume:
  postgres_data:
