services:
  django_drf:
    image: memphistools/public_repo:dummy_django_restframework
    container_name: django_drf
    command:
      sh -c "gunicorn dummy_django_restframework.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/media
    expose:
      - 8000
    environment:
      - DEBUG
      - SECRET_KEY
      - ADMIN_PASSWORD
      - DEFAULT_USER_PASSWORD
      - DJANGO_ALLOWED_HOSTS
      - CORS_ALLOWED_ORIGINS
      - MONGO_SERVER
      - MONGO_PORT
      - MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_ENGINE
      - POSTGRES_PORT

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx
    volumes:
      - static_volume:/home/dummy-operator/web/staticfiles
      - media_volume:/home/dummy-operator/web/media
      - ./certs:/etc/nginx/certs
    ports:
      - 443:443
    depends_on:
      - django_drf

  db:
    image: postgres:17.5-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  dummy_mongo:
    image: mongo:latest
    container_name: dummy_mongodb_movies
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  media_volume:
  static_volume:
  mongo-data:
  postgres_data:
