name: PyLint, Flake & Test

on:
  push:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r dummy_django_restframework/requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint dummy_django_restframework/dummy_django_restframework/ --output=lint.txt || true
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lint.txt
        path: lint.txt
    - name: Lint with flake8
      run: |
        flake8 dummy_django_restframework/movies/ --max-line-length=127 --count --statistics

    - name: Run Tests and Upload Coverage
      env:
        SECRET_KEY: "dummy-secret-key"
        DEFAULT_USER_PASSWORD: "dummy-password"
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        POSTGRES_HOST: "localhost"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "we_dont_care"
        POSTGRES_DB: "movies_db"
        POSTGRES_PORT: "5432"
        POSTGRES_ENGINE: "django.db.backends.postgresql"
        MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
        MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
      run: |
        docker compose -f docker-compose-init.yml up -d
        export PYTHONPATH=$PYTHONPATH:./dummy_django_restframework
        coverage run -m pytest
        coverage report
        coveralls
